### ISSUE TITLE
Suggested settings still break traditional sorting systems.

### ISSUE THREAD

**Issue by Hitaxas** [BananaBaagel/Fast-Hoppers#4]
Tried this on a server, it absolutely breaks sorting systems, no matter what the tick speed or the items per transfer are set to. Items delete themselves from existence.

**Comment by BananaBagel** [comment]
Hi! Could you tell me what MC version you're using, what your storage system looks like, and any other mods you're using? Thanks!

**Comment by Hitaxas** [comment]
The version is 1.20.1. The storage system in question is exactly like in this video by [Voltrox] (https://www.youtube.com/@Voltrox)https://www.youtube.com/watch?v=PVzWp8QHkL0)

The only other mods being used are a few that fix issues with lighting, cpu and memory issues. then Plasmo Voice for prox chat. Everything else is client side, which shouldn't affect anything. 

I am only OP for the server, so I don't have an exact list of the mods, but I assume none of those would have adverse affects on this mod.

**Comment by BananaBagel** [comment]
I don't think any mod should have adverse effects on this but I can't seem to reproduce the problem.
I tried running a 1.20.1 server with fast hoppers 0.2.1, fabric api 90.0.0, and carpet 1.4.112 (for changing the ticks/sec of the game to speed up testing storage layouts). I couldn't reproduce the issue of items disappearing. At most, I had a hopper that moved items along on the same tick that it received them and skipped that sorting column but they still got along to the end of the system fine (using the layout shown in the video). If possible, could you get the list of mods from the owner so I can try to figure out if there is an incompatibility?

**Comment by cronex2011** [comment]
sry for shittalk in there. but can you release your mod for Forge too ?

**Comment by BananaBagel** [comment]
> sry for shittalk in there. but can you release your mod for Forge too ?

no plans to do so right now.
